languageCode = "en-us"
title = "Fluvio - Central control for data-in-motion"

[params]
  blog_time_format = "January 02, 2006"

[menu]
  [[menu.main]]
    identifier = "docs"
    name = "Docs"
    url = "/docs/"
    weight = 100

  [[not-used.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 110

  [[menu.main]]
    identifier = "faq"
    name = "FAQ"
    url = "/faq/"
    weight = 120

  [[menu.main]]
    identifier = "github"
    name = "github"
    url = "https://github.com/infinyon/fluvio"
    pre = "fab fa-github"
    weight = 130

  [[menu.main]]
    identifier = "twitter"
    name = "twitter"
    url = "https://twitter.com/infinyon"
    pre = "fab fa-twitter"
    weight = 140

  [[notused.menu.main]]
    identifier = "contact"
    name = "contact"
    url = "/contact"
    pre = "fas fa-envelope"
    weight = 150    