languageCode = "en-us"
title = "Fluvio"

pygmentsUseClasses=true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[params]
  version = "1.0.2"
  blog_time_format = "January 02, 2006"

[menu]
  [[menu.main]]
    identifier = "docs"
    name = "Docs"
    url = "/docs/"
    weight = 100

  [[menu.main]]
    identifier = "rust"
    name = "Rust API"
    url = "https://docs.rs/flv-client/"
    pre = "fas fa-sm fa-external-link-alt"
    weight = 110

  [[menu.main]]
    identifier = "node"
    name = "Node API"
    url = "https://docs.rs/flv-client/"
    pre = "fas fa-sm fa-external-link-alt"
    weight = 120

  [[hidden.menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    pre = "fab fab-sm fa-blogger"
    weight = 130

  [[menu.main]]
    identifier = "github"
    name = "github"
    url = "https://github.com/infinyon/fluvio"
    pre = "fab fa-github"
    weight = 150

  [[menu.main]]
    identifier = "chat"
    name = "chat"
    url = "https://discordapp.com/invite/bBG2dTz"
    pre = "fab fa-discord"
    weight = 160
