languageCode = "en-us"
title = "Fluvio"

enableRobotsTXT = true
pygmentsUseClasses = true
enableEmoji = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"  

[params]
  version = "2.0.0"
  description = "Real-time Data Streaming Platform"
  company_url = "https://www.infinyon.com"

[menu]
  [[menu.main]]
    identifier = "docs"
    name = "Docs"
    url = "/docs/"
    weight = 100

  [[menu.main]]
    identifier = "cli"
    name = "CLI"
    url = "/cli/"
    weight = 101

  [[menu.main]]
    identifier = "api"
    name = "APIs"
    url = "/api/"
    weight = 103

  [[menu.main]]
    identifier = "chat"
    url = "https://discordapp.com/invite/bBG2dTz"
    pre = "fab fa-discord"
    weight = 160
