languageCode = "en-us"
title = "Fluvio"

enableRobotsTXT = true
<<<<<<< HEAD
pygmentsUseClasses=true
enableEmoji=true
disqusShortname = "fluvio"
=======
pygmentsUseClasses = true
enableEmoji = true
>>>>>>> 237188025ec11f3213748b5da261877cd49c7858

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"  

[params]
  version = "2.0.0"
  description = "Real-time Data Streaming Platform"
  company_url = "https://www.infinyon.com"
  company_logo = "/images/assets/infinyon-with-text.svg"
  site_logo = "/images/assets/fluvio-with-text.svg"

[menu]
  [[menu.fluvio]]
    identifier = "docs"
    name = "Docs"
    url = "/docs/"
    weight = 100

  [[menu.fluvio]]
    identifier = "cli"
    name = "CLI"
    url = "/cli/"
    weight = 101

  [[menu.fluvio]]
    identifier = "api"
    name = "APIs"
    url = "/api/"
    weight = 103

  [[menu.fluvio]]
    identifier = "chat"
    url = "https://discordapp.com/invite/bBG2dTz"
    pre = "fab fa-discord"
    weight = 160

  [[menu.infinyon]]
    identifier = "blog"
    name = "Blog"
    url = "https://www.infinyon.com/blog"
    pre = "fab fa-blogger"
    weight = 100


  [[menu.infinyon]]
    identifier = "tutorials"
    name = "Tutorials"
    url = "https://www.infinyon.com/tutorials"
    pre = "fas fa-graduation-cap"
    weight = 110

  [[menu.infinyon]]
    identifier = "use-cases"
    name = "Use Cases"
    url = "https://www.infinyon.com/use-cases"
    pre = "fas fa-grip-vertical"
    weight = 120